### ISSUE TITLE
FetchError: invalid json response body

### ISSUE THREAD

**Issue by lewebsimple** [anbraten/gitea-js#1]
I get an invalid json response body when trying to use the library with `cross-fetch`.

```
import { giteaApi } from "gitea-js";
import fetch from "cross-fetch";

const api = giteaApi("https://gitea.mydomain.com/", {
  token: "token...here",
  customFetch: fetch,
});

(async () => {
  try {
    const orgs = await api.orgs.orgGetAll();
    console.log(orgs);
  } catch (error) {
    console.error(error);
  }
})();
```

I get the correct response when simulating the call in Postman, the difference being in the Authorization header where I use `Bearer <token>` instead of `token <token>`. I don't know if it makes a difference?

**Comment by anbraten** [comment]
Sorry for the late reply. I guess it could be problem with the Gitea (api) version. I will try to reproduce it and may change the versioning of this lib so it relates to the Gitea versioning.

**Comment by anbraten** [comment]
@lewebsimple I finally released the lib for different Gitea versions. Could you give it a try again and check if it works for you?

**Comment by lewebsimple** [comment]
Working OK now !

**Comment by anbraten** [comment]
Awesome
