### ISSUE TITLE
Token does not work.

### ISSUE THREAD

**Issue by Piero512** [anbraten/gitea-js#11]
The token parameter does not work, as it incorrectly uses Authorization: token <token> instead of Authorization : Bearer <token>.

It was addressed in this fork https://github.com/anbraten/gitea-js/compare/main...lewebsimple:gitea-js:main

**Comment by anbraten** [comment]
Did they (gitea) changed that in a newer version?

**Comment by Piero512** [comment]
I believe that using Bearer is an http standard, while token might have
worked once.

**Comment by anbraten** [comment]
https://github.com/anbraten/gitea-js/commit/40ddf207847768b7b8dc9ea8eb1de7043016f514
