### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by philkunz** [anbraten/gitea-js#8]
The documentation is obviously not correct.
The variable names of things being imported and the ones being used are not matching.

**Comment by anbraten** [comment]
Could you give an example. Seems to work fine for me 🤔

**Comment by philkunz** [comment]
```typescript
import { Api } from 'gitea-js';

const api = new giteaApi('https://try.gitea.com/', {
  token: 'access-token', // generate one at https://gitea.example.com/user/settings/applications
});

const repo = api.repos.repoGet('anbraten', 'gitea-js');
console.log(repo);
```

You import Api, but you instantiate giteaApi ... ;)

**Comment by anbraten** [comment]
Ahh you were referring to the code in the readme. Updated that sample.
