### ISSUE TITLE
TypeScript error when using sample from README

### ISSUE THREAD

**Issue by acherkashin** [anbraten/gitea-js#9]
Error 

```
'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.ts(7009)
```

<img width="940" alt="image" src="https://github.com/anbraten/gitea-js/assets/9947582/7704de38-8732-411f-88bf-2e8a42522492">

<img width="904" alt="image" src="https://github.com/anbraten/gitea-js/assets/9947582/510aa503-b0f3-4d8b-8c3d-fedfcb5ce356">

I guess, new is unnecessary here

**Comment by anbraten** [comment]
Yep, I think I just forgot to update it. Would you like to open a PR to adjust it?

**Comment by acherkashin** [comment]
@anbraten I think I could submit a PR this week to fix it 👍 
Thank you for offering this opportunity!

**Comment by acherkashin** [comment]
@anbraten it is here https://github.com/anbraten/gitea-js/pull/10
